ratings:
  namespace: student16-bookinfo-prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
  image: ghcr.io/chayanpx/bookinfo-details
  tag: prd
ingress:
  host: itkmitl.bookinfo.opsta.net
  path: "/student16/details(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
